// Auto generated file, do not tamper
#ifdef INCLUDE_CONFIG_HEADER
#ifndef _CONFIG_HEADER_H
#define _CONFIG_HEADER_H
#define ARCH_STM32
#define PROC_STM32F1
#define STM32F10X_HD
#define USE_STDPERIPH_DRIVER
#define USER_HARDFAULT
#define CONFIG_MEMOPS
#define CONFIG_VARCALL
#define CONFIG_MATH
#define CONFIG_MINIUTILS
#define CONFIG_TASK_QUEUE
#define CONFIG_RINGBUF
#define CONFIG_UART
#define CONFIG_WIFI232
#define CONFIG_I2C
#define CONFIG_I2C_DEVICE
#define CONFIG_LSM303
#define CONFIG_SPI
#define CONFIG_SPI_DEVICE
#define CONFIG_SPI_FLASH
#define CONFIG_SPI_FLASH_M25P16
#define CONFIG_SPI_DEVICE_OS
#define CONFIG_SPI_FLASH_OS
#define CONFIG_USB_VCD
#define CONFIG_OS
#define CONFIG_SHARED_MEM
#define CONFIG_BOOTLOADER
#endif
#endif
